### ISSUE TITLE
Errors not highlighting when using ssh

### ISSUE THREAD

**Issue by david-collingwood** [SiebelsTim/hack-sublime#11]
I'm using hack through vagrant on OSX and I've had success in setting up the ssh options and getting the plugin to display the errors in the console. However I've had a bit of trouble trying to get it to actually highlight the errors in the code. So I did a bit of digging and added a couple of logs and found that it was breaking out of the loop if it couldn't find the file open in a window. Sublime is running the files from my local machine which looks something like "/Users/davidcollingwood/Code/somefile.php", whereas the path returned by hh_client looks more like "/vagrant/Code/somefile.php". I'm not sure what the best solution to this problem would be, so I thought I would pose it to you before I went and tried to change anything.

**Comment by SiebelsTim** [comment]
Hi,

thank you very much for reporting this and even finding the problem!

You are right, this is an unpleasant problem. 

I'm out of town for a week, hopefully I can look at this more closely then.

**Comment by SiebelsTim** [comment]
Closed in https://github.com/SiebelsTim/hack-sublime/commit/6e1f9dae3809612fcbec69e1e1ac0bcbfa436f08

Thank you so much :)
