### ISSUE TITLE
Vagrant on Windows

### ISSUE THREAD

**Issue by aewing** [SiebelsTim/hack-sublime#6]
I am trying to use this plugin on Windows. I have a vagrant machine running Ubuntu. I have used ssh-copy-id to configure access from my user. My Preferences - Settings - User looks like the following:
```json
{
	"color_scheme": "Packages/Tomorrow Color Schemes/Tomorrow-Night-Eighties.tmTheme",
	"hack_ssh_address": "aewing@10.0.0.2",
	"hack_ssh_enable": true,
	"hack_ssh_folder": "/var/www",
	"ignored_packages":
	[
		"Vintage"
	]
}
```
But nothing happens when I save my files.

**Comment by SiebelsTim** [comment]
Hi, sorry to hear this. Could you look for errors in the console when saving? (`View => Show Console`)

I imagine the `ssh.exe` is not available on your system. People told me you can fetch it by installing cygwin.

**Comment by SiebelsTim** [comment]
Closing for now as I need more information. Feel free to reopen :)
